GameMob/Models/FAQ.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public int idFAQ { get; set; }
        public string nameFAQ { get; set; }
        public string describeFAQ { get; set; }
    }
}

GameMob/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameMob.Models;

namespace GameMob.Controllers
{
    public class CategoryController : Controller
    {
        GameStoreDBEntities db = new GameStoreDBEntities();
        public ActionResult PartialCategoriesLeft()
        {
            var listCategory = db.Genres.ToList();
            return PartialView(listCategory);
        }

        public ActionResult CategoryDetails(int? id)
        {
            //var listGame = new List<Game>();
            //var genres = db.Genres;
            //for (int i = 0; i < db.Genres.Count(); i++) {
            //    var game = db.Games.Where(x => x.Genres.ElementAt(i).idGenre == id);

            //    listGame.Equals(game);  
            
            //}
            var gen = db.Genres.Find(id);
            ViewBag.NameGen = gen.nameGenre;

            var listGame = db.Games.Where(g=>g.Genres.Any(gn => gn.idGenre==id)).OrderByDescending(y => y.namSX).ToList();
            //foreach(var gen in genres){
            //    listGame.Add(new Game
            //    {
                    
            //    });
            //}
            
            

            return View(listGame);
        }
    }
}

GameMob/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GameMob.Models;
using PagedList;
using PagedList.Mvc;


namespace GameMob.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        GameStoreDBEntities db = new GameStoreDBEntities();

        public PartialViewResult PartialContentLeft(int? page)
        {

            var listGame = db.Games.OrderByDescending(n => n.pointOfCritic).ToList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            int m = listGame.Count();
            return PartialView(listGame.ToPagedList(pageNumber, pageSize));
        }

        public PartialViewResult PartialContentRight()
        {

            var listGame = db.Games.OrderByDescending(n => n.luotDownLoad).Take(10).ToList();
            
            return PartialView(listGame);
        }


        static int idGamee = 0;
        public ActionResult Details(int? id)
        {   
            

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }

            if (game.idSeries == null)
            {
                ViewBag.IdSeries = 0;                
            }
            else {
                ViewBag.IdSeries = 1;
            }
           
            idGamee = (int) game.idGame;
            
            return View(game);
       
        }

        
        public ActionResult PartialRelatedSeries(int? id)
        {
            var gamesOfSeries = db.Games.Where(idGame => idGame.idSeries == id).OrderByDescending(n =>n.namSX).ToList();

            /*var sg = db.SeriesGames.Find(id);
            ViewBag.NameSG = sg.nameSeries;
            */

            ViewBag.ID = idGamee;
            return View(gamesOfSeries);
        }

        public ActionResult Download()
        {
            return View();
        }

        public ActionResult PartialNewGame(int? page)
        {
            var listNewGame = db.Games.Where(year => year.namSX == (DateTime.Now.Year)).OrderByDescending(n => n.luotDownLoad).ToList(); 
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            
            return PartialView(listNewGame.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult PartialSlider()
        {
            var game = db.Games.Take(5).OrderBy(y => y.namSX).ToList();
            return PartialView(game);
        }

        public ActionResult GameOnline()
        {
            return View();
        }
        public ActionResult GameOffline()
        {
            return View();
        }

    }
}

GameMob/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameMob.Models;
using PagedList;
using PagedList.Mvc;


namespace GameMob.Controllers
{
    public class HomeController : Controller
    {
        GameStoreDBEntities db = new GameStoreDBEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NewGame()
        {
            return View();
        }

        public ActionResult News()
        {
            return View();
        } 
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult FAQs()
        {
            return View();

        }

        
    }
}

GameMob/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameMob.Models;
using PagedList;
using PagedList.Mvc;

namespace GameMob.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        GameStoreDBEntities db = new GameStoreDBEntities();
        [HttpGet]
        public ActionResult SearchResult(string currentFilter, string searchString, int? page)
        {
            //string gkeyword = f["txtSearch"].ToString();
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var games = from g in db.Games select g;

            if (!String.IsNullOrEmpty(searchString))
            {
                games = games.Where(n => n.nameGame.Contains(searchString));
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);

            if (games.ToList().Count == 0)
            {
                ViewBag.Notif = "Không tìm thấy Game";
            }
            else ViewBag.Notif = "Tìm thấy " + games.ToList().Count + " kết quả";

            return View(games.OrderBy(y => y.namSX).ToPagedList(pageNumber, pageSize));

        }

    }
}

GameMob/Views/Home/FAQs.cshtml
@{
    ViewBag.Title = "FQAs";
    Layout = "~/Views/MyLayout/UserLayout.cshtml";
}

<h2>FAQs</h2>

GameMob/Views/Home/Index.cshtml
@{
    Layout = "~/Views/MyLayout/UserLayout.cshtml";
    ViewBag.Title = "Home Page";
}

<!-- banner -->
@section Home{
<li class="active"><a href="@Url.Action("Index", "Home")">Home</a></li>
}
<div class="banner">
    <!-- slider -->
    <!--- img-slider --->
    <div class="img-slider">
        <!----start-slider-script---->
        <script src="~/Scripts/Js/responsiveslides.min.js"></script>
        <script>
            // You can also use "$(window).load(function() {"
            $(function () {
                // Slideshow 4
                $("#slider4").responsiveSlides({
                    auto: true,
                    pager: true,
                    nav: true,
                    speed: 500,
                    namespace: "callbacks",
                    before: function () {
                        $('.events').append("<li>before event fired.</li>");
                    },
                    after: function () {
                        $('.events').append("<li>after event fired.</li>");
                    }
                });

            });
        </script>
        <!----//End-slider-script---->
        <!-- Slideshow 4 -->
        @Html.Partial("~/Views/Home/PartialSlider.cshtml")
         <!-- slider -->
        <div class="clearfix"> </div>
    </div> <!-- banner -->
    <!-- categories -->

    @Html.Partial("~/Views/Home/PartialCategories.cshtml")

    <!-- categories -->
    <!-- content -->
    <div class="content">
        <div class="container">
            <!-- content-left -->
            <div class="col-md-9 content-left">

                @Html.Action("PartialContentLeft", "Game")
                
            </div>             <!-- End content-left -->
            <!-- content-right -->
            <div class="col-md-3 content-right">
                @Html.Action("PartialContentRight", "Game")
                <!-- content-right -->
            </div>
        </div>
    </div>
    <!-- content -->

GameMob/Views/Home/NewGame.cshtml
@{
    Layout = "~/Views/MyLayout/UserLayout.cshtml";
    ViewBag.Title = "New Game";
}


@section NewGame{
    <li class="active"><a href="@Url.Action("NewGame", "Home")">New Game</a></li>
}

@Html.Partial("~/Views/Home/PartialCategories.cshtml")
<!-- categories -->
<!-- content -->

<div class="content">
    <div class="container">


        <!-- content-left -->

        <div class="col-md-9 content-left">
            <div class="albums">
                <h1>Game Mới</h1>
            </div>

                @Html.Action("PartialNewGame", "Game")
                <div class="clearfix"> </div>
                <!-- pagenate -->
                <!-- pagenate -->
            </div>             <!-- End content-left -->
        <!-- content-right -->
        <div class="col-md-3 content-right">
            @Html.Action("PartialContentRight", "Game")
            <!-- content-right -->
        </div>
    </div>
</div>
<!-- content -->

GameMob/Views/Home/News.cshtml
@{
    Layout = "~/Views/MyLayout/UserLayout.cshtml";
    ViewBag.Title = "Game Online";
}


@section News{
    <li class="active"><a href="@Url.Action("News", "Game")">News</a></li>
}
<h2>News</h2>

GameMob/Views/Home/PartialCategories.cshtml
<div class="categories c-cate">
    <div class="container">
        

        @Html.Action("PartialCategoriesLeft", "Category")
     




        <div class="categories-right">
            @using (Html.BeginForm("SearchResult", "Search", FormMethod.Get))
            {
                @Html.TextBox("searchString", "", htmlAttributes: new { @class = "textBoxSearch", @placeholder = "Search here"})
                <input type="submit" value="search" />
            }
                        
                
            
        </div>
        <div class="clearfix"> </div>
    </div>
</div>

GameMob/Views/Home/PartialSlider.cshtml
<div id="top" class="callbacks_container">
    <ul class="rslides" id="slider4">
        <li>
            <img class="" src="~/IMG/images/slide2.jpg" alt="">
            <div class="slider-caption">
                <div class="slider-caption-title">
                    <h3><span>B</span>at Man: Arkham Knight</h3>
                </div>
                <div class="slider-caption-inner">
                    
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
                    <a class="caption-btn" href="#">Xem Thêm</a>
                </div>
            </div>
        </li>

        <li>
            <img src="~/IMG/images/slide3.jpg" alt="">
            <div class="slider-caption">
                <div class="slider-caption-title">
                    <h3><span>N</span>eed For Speed</h3>
                </div>
                <div class="slider-caption-inner">

                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
                    <a class="caption-btn" href="#">Xem Thêm</a>
                </div>
            </div>
        </li>
        
        <li>
            <img src="~/IMG/images/slide1.jpg" alt="">
            <div class="slider-caption">
                <div class="slider-caption-title">
                    <h3><span>A</span>sasin Creed</h3>
                </div>
                <div class="slider-caption-inner">
                    
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin lectus in quam elementum aliquet. Quisque gravida fringilla velit nec ornare. </p>
                    
                    <a class="caption-btn" href="#">Xem Thêm</a>
                </div>
            </div>
        </li>
                
    </ul>
</div>