GameMob/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GameMob.Models;
using PagedList;
using PagedList.Mvc;


namespace GameMob.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        GameStoreDBEntities db = new GameStoreDBEntities();

        public PartialViewResult PartialContentLeft(int? page)
        {

            var listGame = db.Games.OrderByDescending(n => n.pointOfCritic).ToList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            int m = listGame.Count();
            return PartialView(listGame.ToPagedList(pageNumber, pageSize));
        }

        public PartialViewResult PartialContentRight()
        {

            var listGame = db.Games.OrderByDescending(n => n.luotDownLoad).Take(10).ToList();
            
            return PartialView(listGame);
        }


        static int idGamee = 0;
        public ActionResult Details(int? id)
        {   
            

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }

            if (game.idSeries == null)
            {
                ViewBag.IdSeries = 0;                
            }
            else {
                ViewBag.IdSeries = 1;
            }
           
            idGamee = (int) game.idGame;
            
            return View(game);
       
        }

        
        public ActionResult PartialRelatedSeries(int? id)
        {
            var gamesOfSeries = db.Games.Where(idGame => idGame.idSeries == id).OrderByDescending(n =>n.namSX).ToList();

            /*var sg = db.SeriesGames.Find(id);
            ViewBag.NameSG = sg.nameSeries;
            */

            ViewBag.ID = idGamee;
            return View(gamesOfSeries);
        }

        public ActionResult Download()
        {
            return View();
        }

        public ActionResult PartialNewGame(int? page)
        {
            var listNewGame = db.Games.Where(year => year.namSX == (DateTime.Now.Year)).OrderByDescending(n => n.luotDownLoad).ToList(); 
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            
            return PartialView(listNewGame.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult PartialSlider()
        {
            var game = db.Games.Take(5).OrderBy(y => y.namSX).ToList();
            return PartialView(game);
        }

        public ActionResult GameOnline()
        {
            return View();
        }
        public ActionResult GameOffline()
        {
            return View();
        }

    }
}

GameMob/Controllers/GameSeriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameMob.Models;
using System.Net;
using PagedList;
using PagedList.Mvc;


namespace GameMob.Controllers
{
    public class GameSeriesController : Controller
    {
        // GET: GameSeries

        GameStoreDBEntities db = new GameStoreDBEntities();
        public ActionResult Index(int? page)
        {   
            var listGameSeries = db.SeriesGames.Take(20).ToList();
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(listGameSeries.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult Details(int? id)
        {
            var gamesOfSeries = db.Games.Where(idGame => idGame.idSeries == id).OrderByDescending(y => y.namSX).ToList();            
            
            var sg = db.SeriesGames.Find(id);
            ViewBag.NameSG = sg.nameSeries;
           
            return View(gamesOfSeries);
        }

    }
}

GameMob/Views/GameSeries/Details.cshtml
@using GameMob.Models;
@model List<Game>

@{
    Layout = "~/Views/MyLayout/UserLayout.cshtml";
    ViewBag.Title = "Details";
}

@Html.Partial("~/Views/Home/PartialCategories.cshtml")
@section GameSeries{
    <li class="active"><a href="@Url.Action("Index", "GameSeries")">Game Series</a></li>
}

<div class="content">
    <div class="container">
        <!-- albums -->
        
        <div class="albums">
            <h1>@ViewBag.NameSG Series</h1>
            <div class="album-grids">
                @{
                    foreach (var item in Model)
                    {
                        <div class="album-grid-game">
                            <div class="album-grid-pic">
                                <a href="@Url.Action("Details", "Game", new { id = item.idGame })"><img src="~/IMG/poster/@item.poster" title="name" /></a>
                            </div>
                            <div class="album-grid-info">
                                <p><strong>@item.nameGame</strong> </p>
                                <!--<p><strong>Country:</strong> UK,</p>
                                <p><strong>casting:</strong> <a href="#">Donec,</a><a href="#">variu,</a><a href="#">mauris,</a><a href="#">sociis</a></p>
                                <a class="download-album" href="#">Download</a>-->
                            </div>
                        </div>


                    }
                }


                <div class="clearfix"> </div>
            </div>
            <!-- pagenate -->
            <!-- pagenate -->
        </div>
        <!-- albums -->
    </div>
</div>

GameMob/Views/GameSeries/Index.cshtml
@using GameMob.Models;

@using PagedList.Mvc;
@model PagedList.PagedList<SeriesGame>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/MyLayout/UserLayout.cshtml";
}

@Html.Partial("~/Views/Home/PartialCategories.cshtml")
@section GameSeries{
    <li class="active"><a href="@Url.Action("Index", "GameSeries")">Game Series</a></li>
}

<div class="content">
    <div class="container">
        <!-- albums -->
        <div class="albums">
            <h1>All Series</h1>
            <div class="album-grids">
            @{
                foreach(var item in Model){
                    <div class="album-grid">
                        <div class="album-grid-pic">
                            <a href="@Url.Action("Details", "GameSeries", new { id = item.idSeries })"><img src="~/IMG/imgSeries/@item.imgSeries" title="name" /></a>   
                        </div>
                        <div class="album-grid-info">
                            <p><strong>@item.nameSeries Series</strong> </p>
                            <!--<p><strong>Country:</strong> UK,</p>
                            <p><strong>casting:</strong> <a href="#">Donec,</a><a href="#">variu,</a><a href="#">mauris,</a><a href="#">sociis</a></p>
                            <a class="download-album" href="#">Download</a>-->
                        </div>
                    </div>
                    

                }
}    
                
                
                <div class="clearfix"> </div>
            </div>
            <!-- pagenate -->
            <div>@Html.PagedListPager(Model, page => Url.Action("Index", "GameSeries", new { page = page }))</div>
            <!-- pagenate -->
        </div>
        <!-- albums -->
    </div>
</div>