GameMob/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameMob.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Game()
        {
            return View();
        
        }

        public ActionResult GameSeries()
        {
            return View();
        }

    }
}

GameMob/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GameMob.Models;
using PagedList;
using PagedList.Mvc;


namespace GameMob.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        GameStoreDBEntities db = new GameStoreDBEntities();

        public PartialViewResult PartialContentLeft(int? page)
        {

            var listGame = db.Games.OrderByDescending(n => n.pointOfCritic).ToList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            int m = listGame.Count();
            return PartialView(listGame.ToPagedList(pageNumber, pageSize));
        }

        public PartialViewResult PartialContentRight()
        {

            var listGame = db.Games.OrderByDescending(n => n.luotDownLoad).Take(10).ToList();
            
            return PartialView(listGame);
        }


        static int idGamee = 0;
        public ActionResult Details(int? id)
        {   
            

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }

            if (game.idSeries == null)
            {
                ViewBag.IdSeries = 0;                
            }
            else {
                ViewBag.IdSeries = 1;
            }
           
            idGamee = (int) game.idGame;
            
            return View(game);
       
        }

        
        public ActionResult PartialRelatedSeries(int? id)
        {
            var gamesOfSeries = db.Games.Where(idGame => idGame.idSeries == id).OrderByDescending(n =>n.namSX).ToList();

            /*var sg = db.SeriesGames.Find(id);
            ViewBag.NameSG = sg.nameSeries;
            */

            ViewBag.ID = idGamee;
            return View(gamesOfSeries);
        }

        public ActionResult Download()
        {
            return View();
        }

        public ActionResult PartialNewGame(int? page)
        {
            var listNewGame = db.Games.Where(year => year.namSX == (DateTime.Now.Year)).OrderByDescending(n => n.luotDownLoad).ToList(); 
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            
            return PartialView(listNewGame.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult PartialSlider()
        {
            var game = db.Games.Take(5).OrderBy(y => y.namSX).ToList();
            return PartialView(game);
        }

        public ActionResult GameOnline()
        {
            return View();
        }
        public ActionResult GameOffline()
        {
            return View();
        }

    }
}

GameMob/Views/MyLayout/AdminLoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Material Admin - Login</title>

    <!-- BEGIN META -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="your,keywords">
    <meta name="description" content="Short explanation about this website">
    <!-- END META -->
    <!-- BEGIN STYLESHEETS -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css' />
    <link href="~/Content/CssAdmin/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/CssAdmin/materialadmin.css" rel="stylesheet" />
    <link href="~/Content/CssAdmin/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/CssAdmin/material-design-iconic-font.min.css" rel="stylesheet" />
    <!-- END STYLESHEETS -->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="../../assets/js/libs/utils/html5shiv.js?1403934957"></script>
    <script type="text/javascript" src="../../assets/js/libs/utils/respond.min.js?1403934956"></script>
    <![endif]-->
</head>

<body class="menubar-hoverable header-fixed ">

    <!-- BEGIN LOGIN SECTION -->
    <section class="section-account">
        
        <div class="spacer"></div>
        <div class="card contain-sm style-transparent">
            <!-- <div class="card-body"> -->
            <!-- <div class="row"> -->

            <div class="col-sm-6  col-sm-offset-3">
                <br />
               @RenderBody()
                
                @*<form class="form floating-label" action="@Url.Action("Index","Admin")" accept-charset="utf-8" method="post">
                    <div class="form-group">
                        <input type="text" class="form-control" id="username" name="username">
                        <label for="username">Username</label>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" id="password" name="password">
                        <label for="password">Password</label>
                        <p class="help-block"><a href="#">Forgotten?</a></p>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-xs-6 text-left">
                            <div class="checkbox checkbox-inline checkbox-styled">
                                <label>
                                    <input type="checkbox"> <span>Remember me</span>
                                </label>
                            </div>
                        </div><!--end .col -->
                        <div class="col-xs-6 text-right">
                            <button class="btn btn-primary btn-raised" type="submit">Login</button>
                        </div><!--end .col -->
                    </div><!--end .row -->
                </form>*@
            </div> <!--end .col -->
            <!-- <div class="col-sm-5 col-sm-offset-1 text-center">
                <br><br>
                    <h3 class="text-light">
                        No account yet?
                    </h3>
                    <a class="btn btn-block btn-raised btn-primary" href="#">Sign up here</a>
                    <br><br>
                        <h3 class="text-light">
                            or
                        </h3>
                        <p>
                            <a href="#" class="btn btn-block btn-raised btn-info"><i class="fa fa-facebook pull-left"></i>Login with Facebook</a>
                        </p>
                        <p>
                            <a href="#" class="btn btn-block btn-raised btn-info"><i class="fa fa-twitter pull-left"></i>Login with Twitter</a>
                        </p>
                    </div> -->
            <!--end .col -->
            <!-- </div> --><!--end .row -->
            <!-- </div> --><!--end .card-body -->
        </div><!--end .card -->
    </section>
    <!-- BEGIN JAVASCRIPT -->
    <script src="~/Scripts/jquery-1.11.2.min.js"></script>
    <script src="~/Scripts/jquery-migrate-1.2.1.min.js"></script>


    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/spin.min.js"></script>
    <script src="~/Scripts/jquery.autosize.min.js"></script>
    <script src="~/Scripts/jquery.nanoscroller.min.js"></script>

    <script src="~/Scripts/App.js"></script>
    <script src="~/Scripts/AppCard.js"></script>
    <script src="~/Scripts/AppForm.js"></script>
    <script src="~/Scripts/AppNavigation.js"></script>
    <script src="~/Scripts/AppNavSearch.js"></script>
    <script src="~/Scripts/AppOffcanvas.js"></script>
    <script src="~/Scripts/AppVendor.js"></script>
    <script src="~/Scripts/Demo.js"></script>
    <!-- END JAVASCRIPT -->
    
</body>
</html>

GameMob/Views/MyLayout/UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>

    <title>Game Store</title>
    <meta charset="utf-8">

    <link href="~/Content/Css/bootstrap.css" rel="stylesheet" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <script src="~/Scripts/Js/jquery.min.js"></script>
    <!-- Custom Theme files -->

    <link href="~/Content/Css/style.css" rel="stylesheet" />

    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts--->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,700,800,400,600' rel='stylesheet' type='text/css'>
    <!---//webfonts--->
</head>
<body>
    <!-- container -->
    <div class="header">
        <div class="container">
            <!-- header -->
            <!-- logo -->
            <div class="logo">
                <a href="@Url.Action("Index", "Home")"><img src="~/IMG/logo.png" title="gameStore" /></a>
            </div>
            <!-- logo -->
            <!-- top-nav -->
            <div class="top-nav">
                <span class="menu"> </span>
                <ul>
                    @if (IsSectionDefined("Home"))
                    {
                        @RenderSection("Home")
                    }
                    else
                    {
                        <li><a href="@Url.Action("Index", "Home")">HOME<span> </span></a></li>
                    }

                    @if (IsSectionDefined("NewGame"))
                    {
                        @RenderSection("NewGame")
                    }
                    else
                    {
                        <li><a href="@Url.Action("NewGame", "Home")">New Game</a></li>
                    }
                    @*@if (IsSectionDefined("GameOnline"))
                    {
                        @RenderSection("GameOnline")
                    }
                    else
                    {
                        <li><a href="@Url.Action("GameOnline", "Game")">Game Online</a></li>
                    }*@
                    @if (IsSectionDefined("News"))
                    {
                        @RenderSection("News")
                    }
                    else
                    {
                        <li><a href="@Url.Action("News", "Home")">News</a></li>
                    }

                    @if (IsSectionDefined("GameSeries"))
                    {
                        @RenderSection("GameSeries")
                    }
                    else
                    {
                        <li><a href="@Url.Action("Index", "GameSeries")">Game Series</a></li>
                    }
                    @if (IsSectionDefined("FAQS"))
                    {
                        @RenderSection("FAQS")
                    }
                    else
                    {
                        <li><a href="@Url.Action("FAQs", "Home")">FAQs</a></li>
                    }
                     
                    
                       
                    
                    
                    <div class="clearfix"> </div>
                </ul>
            </div>
            <div class="clearfix"> </div>
            <!-- top-nav -->
            <!-- script-for-menu -->
            <script>
					$(document).ready(function(){
						$("span.menu").click(function(){
							$(".top-nav ul").slideToggle(200);
						});
					});
            </script>
            <!-- script-for-menu -->
        </div>
        <!-- header -->
    </div>
    <!-- banner -->
    <!-- footer -->
    @RenderBody()
  
    <div class="footer">
        <div class="container">
            <div class="footer-grids">
                <div class="col-md-4">
                    <div class="footer-grid">
                        <h5>Giới thiệu Game Store</h5>
                        <p>Website chia sẻ games free tốt nhất, được xây dựng từ năm 2016 với hàng ngàn game nổi tiếng đến từ Ubisoft, RockStar, EA, Konami... Không những thế chúng tôi còn cập nhật tin tức mới nhất của làng Game trong nước và thế giới. </p>
                       
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="footer-grid site-map">
                        <h5>Kết nối</h5>
                        <ul>
                            <li><a href="index.html"><span> </span>Facebook</a></li>
                            <li><a href="404.html"><span> </span>Twitter</a></li>
                            <li><a href="albums.html"><span> </span>Youtube</a></li>

                        </ul>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="footer-grid site-map">
                        <h5>Site Map</h5>
                        <ul>
                            <li><a href="index.html"><span> </span>Home</a></li>
                            <li><a href="404.html"><span> </span>New Game</a></li>
                            <li><a href="albums.html"><span> </span>Game Online</a></li>
                            <li><a href="404.html"><span> </span>Game Offline</a></li>
                            <li><a href="contact.html"><span> </span>GameSeries</a></li>
                            <li><a href="contact.html"><span> </span>FAQs</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="footer-grid f-gallery">
                        <h5>My Partner</h5>
                        <div class="f-gallery-grids">
                            <div class="f-gallery-grid">
                                <ul>
                                    <li><a href="#"><img src="~/IMG/Partner/partner1.jpg" title="name"></a></li>
                                    <li><a href="#"><img src="~/IMG/Partner/partner2.jpg" title="name"></a></li>
                                    <li><a href="#"><img src="~/IMG/Partner/partner3.jpg" title="name"></a></li>
                                    <li><a href="#"><img src="~/IMG/Partner/partner4.jpg" title="name"></a></li>
                                    <li><a href="#"><img src="~/IMG/Partner/partner5.jpg" title="name"></a></li>
                                    <li><a href="#"><img src="~/IMG/Partner/partner6.jpg" title="name"></a></li>
                                    <div class="clearfix">
                                    </div>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
    <!-- footer -->
    <!-- copy-right -->
    <div class="copy-right">
        <div class="container">
            <p>Copy Right By Franky</a></p>
        </div>
    </div>
    <!-- copy-right -->
    <!-- container -->
</body>
</html>