GameMob/Controllers/GameSeriesManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

using GameMob.Models;
using System.IO;
namespace GameMob.Controllers
{
    public class GameSeriesManagementController : Controller
    {
        GameStoreDBEntities db = new GameStoreDBEntities();
        // GET: GameManagement
        public PartialViewResult ListGameSeries(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;

            return PartialView(db.SeriesGames.OrderByDescending(n => n.nameSeries).ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult CreateNewGameSeries()
        {

            return View();

        }

        [HttpPost]
        public ActionResult CreateNewGameSeries(SeriesGame series, HttpPostedFileBase fileUpload)
        {


            var fileName = Path.GetFileName(fileUpload.FileName);
            var path = Path.Combine(Server.MapPath("~/IMG/imgSeries/"), fileName);
            if (System.IO.File.Exists(path))
            {
                ViewBag.Notif = "This image is already exist!";
            }
            else
            {
                fileUpload.SaveAs(path);
            }
            series.imgSeries = fileUpload.FileName;
            db.SeriesGames.Add(series);
            db.SaveChanges();
            return RedirectToAction("GameSeries", "Admin");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {

            SeriesGame series = db.SeriesGames.SingleOrDefault(n => n.idSeries == id);
            if (series == null)
            {
                Response.StatusCode = 404;
                return null;
            }


            return View(series);
        }

        [HttpPost]
        public ActionResult Edit(SeriesGame series, HttpPostedFileBase fileUpdate)
        {
            SeriesGame seriesEdit = db.SeriesGames.SingleOrDefault(n => n.idSeries == series.idSeries);

            seriesEdit.nameSeries = series.nameSeries;

            if (fileUpdate == null)
            {

            }
            else
            {
                var fileName = Path.GetFileName(fileUpdate.FileName);
                var path = Path.Combine(Server.MapPath("~/IMG/imgSeries/"), fileName);
                if (System.IO.File.Exists(path))
                {
                    ViewBag.Notif = "This image is already exist!";
                }
                else
                {
                    fileUpdate.SaveAs(path);
                }
                series.imgSeries = fileUpdate.FileName;
                seriesEdit.imgSeries = series.imgSeries;
            }


            db.SaveChanges();
            return RedirectToAction("GameSeries", "Admin");

        }


        public ActionResult Delete(int? id)
        {
            SeriesGame series = db.SeriesGames.SingleOrDefault(n => n.idSeries == id);
            var game = db.Games.Where(n => n.idSeries == id).ToList();
            if (series != null) {
                for (int i = 0; i < game.Count(); i++)
                {
                    game.ElementAt(i).idSeries = null;
                }
            db.SeriesGames.Remove(series);
            db.SaveChanges();
            }

            return RedirectToAction("GameSeries", "Admin");
        }
    }
}

GameMob/Views/GameSeriesManagement/CreateNewGameSeries.cshtml
@model GameMob.Models.SeriesGame

@{
    ViewBag.Title = "CreateNewGameSeries";
    Layout = "~/Views/MyLayout/AdminLayout.cshtml";
}



<div class="col-lg-offset-1 col-md-4">
    @using (Html.BeginForm("CreateNewGameSeries", "GameSeriesManagement", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="card-head style-primary">
                <header>Create new game series</header>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
           

            <div class="form-group">
                @Html.LabelFor(model => model.nameSeries, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nameSeries, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nameSeries, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.imgSeries, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="fileUpload">
                    @ViewBag.Notif
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>
    

GameMob/Views/GameSeriesManagement/Edit.cshtml
@model GameMob.Models.SeriesGame

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/MyLayout/AdminLayout.cshtml";
}


<div class="col-lg-offset-1 col-md-6">
    @using (Html.BeginForm("Edit", "GameSeriesManagement", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="card-head style-primary">
                <header>Edit</header>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
          
            @Html.HiddenFor(model => model.idSeries)
            <div class="form-group">
                @Html.LabelFor(model => model.nameSeries, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nameSeries, new { htmlAttributes = new { @class = "form-control" } })
                    
                </div>
            </div>

            
            <div class="form-group">
                @Html.LabelFor(model => model.imgSeries, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="fileUpdate">
                </div>
            </div>

            

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <button class="btn btn-default-bright btn-raised" data-toggle="modal" data-target="#simpleModal">Simple modal</button>
    <div class="modal fade" id="simpleModal" tabindex="-1" role="dialog" aria-labelledby="simpleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="simpleModalLabel">Save changes</h4>
                </div>
                <div class="modal-body">
                    <p>Do you want to save changes?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
</div>

GameMob/Views/GameSeriesManagement/ListGameSeries.cshtml
@using PagedList;
@using PagedList.Mvc;

@model PagedList.PagedList<GameMob.Models.SeriesGame>
@{
    ViewBag.Title = "ListGameSeries";

}

<link href="~/Content/CssAdmin/Table/jquery.dataTables.css" rel="stylesheet" />

<div style="width: 13%; text-align:center">
    <a href="@Url.Action("CreateNewGameSeries", "GameSeriesManagement")" class="btn btn-block ink-reaction btn-lg btn-primary">Create New</a>
</div>
<div class="spacer"></div>
<div class="col-md-6">
    <table id="datatable1" class="table table-striped table-hover dataTable no-footer" role="grid" aria-describedby="datatable1_info">
        <thead>
            <tr role="row">

                <th class="sorting" tabindex="0" aria-controls="datatable1" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 212px;">
                    <h4><b>Tên Game Series</b></h4>
                </th>
                <th class="sorting" tabindex="0" aria-controls="datatable1" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 212px;">
                    <h4><b>Ảnh bìa</b></h4>
                </th>
                <th></th>
                <th></th>


            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="gradeX odd" role="row">

                    <td>
                        @Html.DisplayFor(modelItem => item.nameSeries)
                    </td>

                    <td>
                        <img src="~/IMG/imgSeries/@Html.DisplayFor(modelItem => item.imgSeries) " height="120" width="85" />
                    </td>

                   
                        <td>
                            <a role="button" href="@Url.Action("Edit", "GameSeriesManagement", new {@id = item.idSeries})" class="btn btn-block ink-reaction btn-xs btn-warning">Edit</a>

                        </td>
                        <td><a role="button" href="@Url.Action("Delete", "GameSeriesManagement", new { @id = item.idSeries })" class="btn btn-block ink-reaction btn-xs btn-danger">Delete</a>
                            @*<button class="btn btn-default-bright btn-raised" data-toggle="modal" data-target="#simpleModal">Delete</button>

                            <div class="modal fade" id="simpleModal" tabindex="-1" role="dialog" aria-labelledby="simpleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title" id="simpleModalLabel">Save changes</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>Do you want to save changes?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                            @*<button type="button" class="btn btn-primary">Save changes</button>*@
                                            
                                        @*</div>
                                    </div><!-- /.modal-content -->
                                </div><!-- /.modal-dialog -->
                            </div>*@   
                        </td>

                   
                </tr>
            }
        </tbody>
    </table><div>@Html.PagedListPager(Model, page => Url.Action("GameSeries", "Admin", new { page = page }))</div>
</div>